# 配置文件，在这里填写api

weatherXinZhi: SeSI8hL-BdFhE9MKb #心知天气api   从https://www.seniverse.com/注册获取
sauceno-api: b1f018dbf8b7c21c38b4d9ad0211f8db1c4eaf20 #sauceno搜图api，你可以从https://saucenao.com/user.php注册并获取
moderate: 6fb083462b3806a00545ddae4c3f2a5b #色图审核api 从https://www.moderatecontent.com/获取
siZhiAi:                         #思知ai，已不建议使用，建议用ai，如果你还是想用。从https://console.ownthink.com/login
- 80f
- '806'
- fg
nasa_api: kLzPMrV #nasa相关天文api 从https://api.nasa.gov/index.html#main-content申请
chatGLM: 69ef5.GxN2sfHvsQNjvpXi  #chatGLM的apiKey，从https://open.bigmodel.cn/获取
gemini:                          #谷歌的gemini api，免费的，有几个填几个，在https://ai.google.dev/tutorials/setup?hl=zh-cn获取，需要配置代理，否则无法使用
- AIzQ7CC31SXi5rNk
- AIzaSyCGZOsWmC2n2HbvLWkOg
openai-keys:                     #openai官方的apikey，或免费(不推荐，已经加了限制。random模式够你用了)从https://github.com/chatanywhere/GPT_API_free?tab=readme-ov-file申请
- sk-McohJBxaA2QpyVxh5zVT5EUPrB66WUPTCZ4lyDyMVwOdXeQx
- ffff
gpt3.5-dev: true                 #如果是从https://github.com/chatanywhere/GPT_API_free?tab=readme-ov-file申请openai-apikey，请打开此开关，这样就无需代理即可使用
bing-image-creator:              #bing的ai绘画，参考https://github.com/avilliai/Manyana/issues/8
  _U: 
    19vnVzP4nhA5PCT_RAZY6NCP71gga4R6diQ7Ok59hdsUkV2PF9v9jaTQnShVjc2X1lbqePwZ7IeBRCvONfe-TeGoWN2LCbnw
  KievRPSSecAuth: FABi
proxy: http://127.0.0.1:10809    #代理 http://127.0.0.1:端口 如http://127.0.0.1:10809 自己设置对应的端口，没有就不填，v2ray一般是10809，clash一般7890，ssr一般1080
sock5-proxy: socks5://127.0.0.1:10808 #sock5代理，如使用bing-imagecreator必须配置，取决于你自己代理的端口。
GeminiRevProxy: '' #基于cloudflare反向代理，整好了能裸连Gemini，自己折腾去，完事填你自己的域名
cozi: https://avillia.zeabur.app/v1/chat/completions # https://github.com/avilliai/Manyana/issues/4
modelscopeCookie: ''            #modescopeTTS增加反爬虫，默认留空用我的，如不能用了自行抓取cookie，查看https://github.com/avilliai/Manyana/issues/7
bert_colab: https://mess-addressed-openings-exposed.trycloudflare.com/synthesize        #新版本Manyana无需配置此功能，语音合成选modelscopeTTS模式可直接使用。但如果你喜欢折腾：bert_vits_colab部署：https://colab.research.google.com/drive/1n8lI6pOiDtli2zC5fL9PZ9TZqbOafqma?usp=sharing 请注意，使用此功能必须配置上面的proxy项

